import type { Metadata } from "next";
import "./globals.css";
import { inter } from "@/lib/fonts";

import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider/theme-provider";
import Navbar from "@/components/navbar/navbar";

export const metadata: Metadata = {
	title: "aiNotes",
	description: "Generated by create next app"
};
export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ClerkProvider>
			<html lang="en" suppressHydrationWarning>
				<body className={`${inter.className}  overflow-x-hidden`}>
					<ThemeProvider attribute="class" defaultTheme="light">
						<div className="relative mx-auto  flex w-screen max-w-7xl  flex-col items-center justify-start  space-y-8">
							<Navbar />
							{children}
						</div>
					</ThemeProvider>
				</body>
			</html>
		</ClerkProvider>
	);
}
